- name: Transfer and execute a script.
  hosts: all
  user: root
  tasks:
    - name: Copy and Execute the script
      script: ./scripts/check_disk_size1.sh

    - name: get contents of file
      command: cat /tmp/check_disk_size1.log
      register: filename
      become: true

    - name: viewing the contents
      debug:
        msg: "{{ filename.stdout_lines }}"
