- name: Transfer and execute a script.
  hosts: all
  user: root
  tasks:
    - name: Copy and Execute the script
      script: /srv/__projects/ansible-playbooks/playbooks/samples/scripts/query_endpoints.sh

    - name: get contents of file
      command: cat /tmp/query_endpoints.log
      register: filename
      become: true

    - name: viewing the contents
      debug:
        msg: "{{ filename.stdout_lines }}"
