- name: Transfer and execute a script.
  hosts: all
  user: root
  tasks:
    - name: Creates directory
      file:
        path: /root/@1
        state: directory
        owner: root
        group: root
        mode: 0775

    - name: Copy and Execute the script 
      script: ./scripts/do-something.sh

    - name: get contents of file
      command: cat /tmp/do-something.log
      register: filename
      become: true

    - name: viewing the contents
      debug:
        msg: "{{filename.stdout}}"
